version: "3"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_ENDPOINT=http://fastapi:8080/normalize_llm
      - NER_ENDPOINT=http://fastapi:8080/normalize_ner

  streamlit:
    build:
      context: .
      dockerfile: Streamlit.dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - LLM_ENDPOINT=http://fastapi:8080/normalize_llm
      - NER_ENDPOINT=http://fastapi:8080/normalize_ner